version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: yassi
      POSTGRES_PASSWORD: Lkjhmng1
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"  # <--- THIS LINE IS CRITICAL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: